### ISSUE TITLE
关于获取函数

### ISSUE THREAD

**Issue by cheng18175030250** [ljqcodelove/ContTune#1]
请问文中的获取函数如何求解呢？以及获取函数中p\*表示“并行度的最小可行水平”是什么意思？我们怎么得到p\*呢？

**Comment by ljqcodelove** [comment]
对不起，我现在才看到这个 issue。
我们对于并发度建立了 X 轴，在目前已有的样本（真实重启，得到了并发度与其对应的处理能力的样本对）里面，一定会有一个并发度比当前流量大（如果没有，我们会反复使用Big算法倍增），那么已有的样本一定可以找到一个最小的并发度p\*满足真实处理能力大于当前流量，在此基础上，我们会用采集函数鼓励找到比当前的并发度p\*小的并法度p（对应论文中式子5，𝑎𝑟𝑔max(𝑝𝑖∗ −𝑝𝑖)𝐼 (𝜇(𝑝𝑖) −𝜆𝑖)），而这个p是需要你遍历并发度从 1 到 pmax，pmax 是Big算法得到的最大并发度。

所以对于获取函数只需要for循环遍历并发度 x，拿到高斯过程中的均值，判断均值是否大于当前流量，只有大于当前流量的认为是安全的，在此基础上找到最小的并发度p，当然如果采集函数取到的值就是 0 的时候（没有比 p\* 更小的并发度满足处理能力大于当前流量），代码会直接选用 p\* 作为 p。

**Comment by ljqcodelove** [comment]
但是实际上这样找到的并发度有可能会使得作业不满足服务等级协议（仅仅根据高斯过程均值，而高斯过程样本少的时候不一定拟合的准），因此我们在Section5.2设计了distance来打分，只有找到的 p 并发度距离任意一个样本的距离小于等于设定的阿尔法值的时候，才认为是准确的（这里利用了一维高斯过程中样本点附近拟合的比较准的性质）。
